apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: base-test
  labels:
    app: nginx
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80