apiVersion: v1
kind: Service
metadata: 
  name: nginx-service
  namespace: base-test
  labels:
    app: nginx
spec: 
  selector: # Targets pods with the pod label nginx
    app: nginx
  ports: # Maps port 80 on service to pod port 80
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort # For localhost testing
  # type: ClusterIP # Makes it reachable in cluster only
