apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'nginx'   # Identitifier
        static_configs:
          - targets: ['nginx-service.base-test.svc.cluster.local:80']  #  # The DNS name of the Nginx service inside the cluster
